"""Shared venue name normalization for all processing scripts."""

# Maps raw Cricsheet venue names to canonical names.
# Built from 1,169 IPL match files.
VENUE_ALIASES = {
    # Chinnaswamy
    "M Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    # Wankhede
    "Wankhede Stadium": "Wankhede Stadium",
    "Wankhede Stadium, Mumbai": "Wankhede Stadium",
    # Eden Gardens
    "Eden Gardens": "Eden Gardens",
    "Eden Gardens, Kolkata": "Eden Gardens",
    # Chepauk
    "MA Chidambaram Stadium": "MA Chidambaram Stadium",
    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",
    "MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",
    # Rajiv Gandhi (Hyderabad)
    "Rajiv Gandhi International Stadium": "Rajiv Gandhi International Stadium",
    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",
    "Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium",
    # Arun Jaitley / Feroz Shah Kotla
    "Arun Jaitley Stadium": "Arun Jaitley Stadium",
    "Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Feroz Shah Kotla Ground": "Arun Jaitley Stadium",
    # Sawai Mansingh
    "Sawai Mansingh Stadium": "Sawai Mansingh Stadium",
    "Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",
    # Punjab / Mohali
    "Punjab Cricket Association IS Bindra Stadium": "IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "IS Bindra Stadium",
    "Punjab Cricket Association Stadium, Mohali": "IS Bindra Stadium",
    "IS Bindra Stadium": "IS Bindra Stadium",
    # Narendra Modi / Motera
    "Narendra Modi Stadium": "Narendra Modi Stadium",
    "Narendra Modi Stadium, Ahmedabad": "Narendra Modi Stadium",
    "Sardar Patel Stadium, Motera": "Narendra Modi Stadium",
    "Sardar Patel (Gujarat) Stadium, Motera": "Narendra Modi Stadium",
    "Gujarat Stadium": "Narendra Modi Stadium",
    # Ekana (Lucknow)
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium": "Ekana Cricket Stadium",
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow": "Ekana Cricket Stadium",
    "BRSABV Ekana Cricket Stadium": "Ekana Cricket Stadium",
    "Ekana Cricket Stadium": "Ekana Cricket Stadium",
    # Dharamsala
    "Himachal Pradesh Cricket Association Stadium": "HPCA Stadium",
    "Himachal Pradesh Cricket Association Stadium, Dharamsala": "HPCA Stadium",
    "HPCA Stadium": "HPCA Stadium",
    # DY Patil
    "Dr DY Patil Sports Academy": "DY Patil Stadium",
    "Dr DY Patil Sports Academy, Mumbai": "DY Patil Stadium",
    "DY Patil Stadium": "DY Patil Stadium",
    # Brabourne
    "Brabourne Stadium": "Brabourne Stadium",
    "Brabourne Stadium, Mumbai": "Brabourne Stadium",
    # Holkar
    "Holkar Cricket Stadium": "Holkar Cricket Stadium",
    "Holkar Cricket Stadium, Indore": "Holkar Cricket Stadium",
    # Barabati
    "Barabati Stadium": "Barabati Stadium",
    "Barabati Stadium, Cuttack": "Barabati Stadium",
    # Newlands
    "Newlands": "Newlands",
    # St George's Park
    "St George's Park": "St George's Park",
    # SuperSport Park
    "SuperSport Park": "SuperSport Park",
    # Sharjah
    "Sharjah Cricket Stadium": "Sharjah Cricket Stadium",
    # Dubai
    "Dubai International Cricket Stadium": "Dubai International Cricket Stadium",
    # Abu Dhabi
    "Sheikh Zayed Stadium": "Sheikh Zayed Stadium",
    "Zayed Cricket Stadium, Abu Dhabi": "Sheikh Zayed Stadium",
    # Others
    "ACA-VDCA Stadium": "ACA-VDCA Stadium",
    "ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": "ACA-VDCA Stadium",
    "Saurashtra Cricket Association Stadium": "Saurashtra Cricket Association Stadium",
    "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur": "Mullanpur Stadium",
    "Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh": "Mullanpur Stadium",
    "Maharashtra Cricket Association Stadium": "MCA Stadium",
    "Maharashtra Cricket Association Stadium, Pune": "MCA Stadium",
    "Subrata Roy Sahara Stadium": "MCA Stadium",
    "MCA International Stadium, Pune": "MCA Stadium",
    "Vidarbha Cricket Association Stadium, Jamtha": "VCA Stadium",
    "Vidarbha Cricket Association Ground, Nagpur": "VCA Stadium",
    "Green Park": "Green Park",
    "Nehru Stadium": "Nehru Stadium",
    # South Africa (T20I + SA20 variants)
    "Kingsmead": "Kingsmead",
    "Kingsmead, Durban": "Kingsmead",
    "SuperSport Park, Centurion": "SuperSport Park",
    "Newlands, Cape Town": "Newlands",
    "St George's Park, Gqeberha": "St George's Park",
    "St George's Park, Port Elizabeth": "St George's Park",
    "New Wanderers Stadium": "New Wanderers Stadium",
    "New Wanderers Stadium, Johannesburg": "New Wanderers Stadium",
    "Boland Park, Paarl": "Boland Park",
    "Boland Park": "Boland Park",
    "Buffalo Park": "Buffalo Park",
    "OUTsurance Oval": "OUTsurance Oval",
    "De Beers Diamond Oval": "De Beers Diamond Oval",
    "Mangaung Oval": "Mangaung Oval",
    "Mangaung Oval, Bloemfontein": "Mangaung Oval",
    # Australia (BBL + T20I variants)
    "Melbourne Cricket Ground": "Melbourne Cricket Ground",
    "Melbourne Cricket Ground, Melbourne": "Melbourne Cricket Ground",
    "Sydney Cricket Ground": "Sydney Cricket Ground",
    "Sydney Cricket Ground, Sydney": "Sydney Cricket Ground",
    "Brisbane Cricket Ground, Woolloongabba": "The Gabba",
    "Brisbane Cricket Ground, Woolloongabba, Brisbane": "The Gabba",
    "The Gabba, Brisbane": "The Gabba",
    "Perth Stadium": "Perth Stadium",
    "Perth Stadium, Perth": "Perth Stadium",
    "W.A.C.A. Ground": "WACA Ground",
    "W.A.C.A. Ground, Perth": "WACA Ground",
    "Docklands Stadium": "Docklands Stadium",
    "Docklands Stadium, Melbourne": "Docklands Stadium",
    "Adelaide Oval": "Adelaide Oval",
    "Adelaide Oval, Adelaide": "Adelaide Oval",
    "Bellerive Oval": "Bellerive Oval",
    "Bellerive Oval, Hobart": "Bellerive Oval",
    "Manuka Oval": "Manuka Oval",
    "Manuka Oval, Canberra": "Manuka Oval",
    "Sydney Showground Stadium": "Sydney Showground Stadium",
    "Showground Stadium, Sydney": "Sydney Showground Stadium",
    "Junction Oval, Melbourne": "Junction Oval",
    # Sri Lanka
    "R.Premadasa Stadium, Khettarama": "R Premadasa Stadium",
    "R Premadasa Stadium": "R Premadasa Stadium",
    "R Premadasa Stadium, Colombo": "R Premadasa Stadium",
    "Rangiri Dambulla International Stadium": "Dambulla Stadium",
    "Rangiri Dambulla International Stadium, Dambulla": "Dambulla Stadium",
    "Pallekele International Cricket Stadium": "Pallekele Stadium",
    "Pallekele International Cricket Stadium, Pallekele": "Pallekele Stadium",
    "Sinhalese Sports Club Ground, Colombo": "SSC Ground",
    "Sinhalese Sports Club Ground": "SSC Ground",
    # Pakistan
    "National Stadium": "National Stadium",
    "National Stadium, Karachi": "National Stadium",
    "Gaddafi Stadium": "Gaddafi Stadium",
    "Gaddafi Stadium, Lahore": "Gaddafi Stadium",
    "Rawalpindi Cricket Stadium": "Rawalpindi Cricket Stadium",
    "Rawalpindi Cricket Stadium, Rawalpindi": "Rawalpindi Cricket Stadium",
    "Multan Cricket Stadium": "Multan Cricket Stadium",
    "Multan Cricket Stadium, Multan": "Multan Cricket Stadium",
    # Bangladesh
    "Shere Bangla National Stadium": "Shere Bangla National Stadium",
    "Shere Bangla National Stadium, Mirpur": "Shere Bangla National Stadium",
    "Shere Bangla National Stadium, Mirpur, Dhaka": "Shere Bangla National Stadium",
    "Zahur Ahmed Chowdhury Stadium": "Zahur Ahmed Chowdhury Stadium",
    "Zahur Ahmed Chowdhury Stadium, Chattogram": "Zahur Ahmed Chowdhury Stadium",
    "Sylhet International Cricket Stadium": "Sylhet International Cricket Stadium",
    "Sylhet International Cricket Stadium, Sylhet": "Sylhet International Cricket Stadium",
    # Caribbean
    "Queen's Park Oval, Port of Spain": "Queen's Park Oval",
    "Queen's Park Oval": "Queen's Park Oval",
    "Kensington Oval, Bridgetown, Barbados": "Kensington Oval",
    "Kensington Oval, Bridgetown": "Kensington Oval",
    "Kensington Oval": "Kensington Oval",
    "Sabina Park, Kingston": "Sabina Park",
    "Sabina Park, Kingston, Jamaica": "Sabina Park",
    "Sabina Park": "Sabina Park",
    "Warner Park, Basseterre, St Kitts": "Warner Park",
    "Warner Park, Basseterre": "Warner Park",
    "Warner Park": "Warner Park",
    "Providence Stadium, Guyana": "Providence Stadium",
    "Providence Stadium": "Providence Stadium",
    "Brian Lara Stadium, Tarouba, Trinidad": "Brian Lara Stadium",
    "Brian Lara Stadium, Tarouba": "Brian Lara Stadium",
    # England
    "Lord's": "Lord's",
    "Lord's, London": "Lord's",
    "The Oval, London": "The Oval",
    "The Oval": "The Oval",
    "Sophia Gardens, Cardiff": "Sophia Gardens",
    "Sophia Gardens": "Sophia Gardens",
    "Edgbaston, Birmingham": "Edgbaston",
    "Edgbaston": "Edgbaston",
    "Old Trafford, Manchester": "Old Trafford",
    "Old Trafford": "Old Trafford",
    "Trent Bridge, Nottingham": "Trent Bridge",
    "Trent Bridge": "Trent Bridge",
    "Headingley, Leeds": "Headingley",
    "Headingley": "Headingley",
    "The Rose Bowl, Southampton": "The Rose Bowl",
    "The Rose Bowl": "The Rose Bowl",
    # New Zealand
    "Eden Park, Auckland": "Eden Park",
    "Eden Park": "Eden Park",
    "Basin Reserve, Wellington": "Basin Reserve",
    "Basin Reserve": "Basin Reserve",
    "Hagley Oval, Christchurch": "Hagley Oval",
    "Hagley Oval": "Hagley Oval",
    "McLean Park, Napier": "McLean Park",
    "McLean Park": "McLean Park",
    "Seddon Park, Hamilton": "Seddon Park",
    "Seddon Park": "Seddon Park",
    "Bay Oval, Mount Maunganui": "Bay Oval",
    "Bay Oval": "Bay Oval",
    # West Indies / misc
    "Saurashtra Cricket Association Stadium, Rajkot": "Saurashtra Cricket Association Stadium",
    "JSCA International Stadium Complex, Ranchi": "JSCA International Stadium Complex",
    # Zimbabwe
    "Harare Sports Club": "Harare Sports Club",
    "Harare Sports Club, Harare": "Harare Sports Club",
}


def normalize_venue(raw_name: str) -> str:
    """Return canonical venue name, or the raw name if no mapping exists."""
    return VENUE_ALIASES.get(raw_name, raw_name)


# Maps canonical venue name → city for display purposes.
# Every venue should be displayable as "Venue, City".
VENUE_CITIES = {
    "M Chinnaswamy Stadium": "Bengaluru",
    "Wankhede Stadium": "Mumbai",
    "Eden Gardens": "Kolkata",
    "MA Chidambaram Stadium": "Chennai",
    "Rajiv Gandhi International Stadium": "Hyderabad",
    "Arun Jaitley Stadium": "Delhi",
    "Sawai Mansingh Stadium": "Jaipur",
    "IS Bindra Stadium": "Mohali",
    "Narendra Modi Stadium": "Ahmedabad",
    "Ekana Cricket Stadium": "Lucknow",
    "HPCA Stadium": "Dharamsala",
    "MCA Stadium": "Pune",
    "DY Patil Stadium": "Navi Mumbai",
    "Brabourne Stadium": "Mumbai",
    "Holkar Cricket Stadium": "Indore",
    "Barabati Stadium": "Cuttack",
    "Mullanpur Stadium": "Chandigarh",
    "ACA-VDCA Stadium": "Visakhapatnam",
    "VCA Stadium": "Nagpur",
    "Saurashtra Cricket Association Stadium": "Rajkot",
    "JSCA International Stadium Complex": "Ranchi",
    "Green Park": "Kanpur",
    "Nehru Stadium": "Kochi",
    # International
    "Dubai International Cricket Stadium": "Dubai",
    "Sharjah Cricket Stadium": "Sharjah",
    "Sheikh Zayed Stadium": "Abu Dhabi",
    "Melbourne Cricket Ground": "Melbourne",
    "Sydney Cricket Ground": "Sydney",
    "The Gabba": "Brisbane",
    "Perth Stadium": "Perth",
    "WACA Ground": "Perth",
    "Adelaide Oval": "Adelaide",
    "Bellerive Oval": "Hobart",
    "Docklands Stadium": "Melbourne",
    "Manuka Oval": "Canberra",
    "Sydney Showground Stadium": "Sydney",
    "Junction Oval": "Melbourne",
    "SuperSport Park": "Centurion",
    "Newlands": "Cape Town",
    "Kingsmead": "Durban",
    "St George's Park": "Gqeberha",
    "New Wanderers Stadium": "Johannesburg",
    "Boland Park": "Paarl",
    "Mangaung Oval": "Bloemfontein",
    "R Premadasa Stadium": "Colombo",
    "Pallekele Stadium": "Kandy",
    "Dambulla Stadium": "Dambulla",
    "SSC Ground": "Colombo",
    "National Stadium": "Karachi",
    "Gaddafi Stadium": "Lahore",
    "Rawalpindi Cricket Stadium": "Rawalpindi",
    "Multan Cricket Stadium": "Multan",
    "Shere Bangla National Stadium": "Dhaka",
    "Zahur Ahmed Chowdhury Stadium": "Chattogram",
    "Sylhet International Cricket Stadium": "Sylhet",
    "Queen's Park Oval": "Port of Spain",
    "Kensington Oval": "Bridgetown",
    "Sabina Park": "Kingston",
    "Warner Park": "Basseterre",
    "Providence Stadium": "Guyana",
    "Brian Lara Stadium": "Tarouba",
    "Lord's": "London",
    "The Oval": "London",
    "Edgbaston": "Birmingham",
    "Old Trafford": "Manchester",
    "Trent Bridge": "Nottingham",
    "Headingley": "Leeds",
    "The Rose Bowl": "Southampton",
    "Sophia Gardens": "Cardiff",
    "Eden Park": "Auckland",
    "Hagley Oval": "Christchurch",
    "Basin Reserve": "Wellington",
    "Seddon Park": "Hamilton",
    "Bay Oval": "Mount Maunganui",
    "McLean Park": "Napier",
    "Harare Sports Club": "Harare",
}


def venue_with_city(canonical_name: str) -> str:
    """Return 'Venue, City' for display. Falls back to just venue name."""
    city = VENUE_CITIES.get(canonical_name)
    if city:
        return f"{canonical_name}, {city}"
    return canonical_name
